baseURL = "https://simplerecipes.now.sh/"
languageCode = "en-us"
title = "Simple Recipes"
theme = "ananke"

[permalinks]
  post = ":slug"
  
[params]
  description = "The place for over 10,000 popular recipes for your complete cooking guide"
  
[author]
    name = "Clara Bernadette"
    homepage = "https://mysuperspecialrecipes.web.app/"
    bio = "True Food Lover"
    image = "https://i.imgur.com/qNQv8nK.jpg"